###

POST {{apiurl}}
Content-Type: application/graphq
x-api-key: {{apikey}}

{
  "query": "query { all(limit: 10, nextToken: \"\") { items { itemId, name } } }"
}

###

POST {{apiurl}}
Content-Type: application/graphq
x-api-key: {{apikey}}

{
  "query": "mutation { save( item: { itemId: \"itemId-6\", name: \"Georg3\", price: 101, meta: { text1: \"huhu\"}}) { itemId } }"
}

###


